const char *name[] = {
	"Arthur",
	"Marcos",
	"Vitor Chiletto",
	"Comunista",
	"Matheus Felcks",
	"Arthur Veterano",
	"Felipe Rangel",
	"Marcelo Zamith",
	"Juliana Zamith",
	"Ubiratam de Paula",
	"Ligia Maria",
	"Filipe Braida",
	"Filipe Duarte",
	"Natalia Schots",
	"Natalia Francisco",
	"Nelson",
	"Igor Brito",
	"Mariana Mendes",
	"Gabriel Filippo",
	"Luis Antonio",
	"Lucas Moraes",
	"Rodrigo R10",
	"Fisica",
	"Quimica",
	"Comp 2",
	"Bruno",
	"Ricardo",
	"Paula",
	"Jose",
	"Maria",
	"Antonio",
	"Gabriel",
	"Vasco da Gama"
};